### ISSUE TITLE
Provide a pin mapping for the 8-pin version of the CC1101

### ISSUE THREAD

**Issue by ElGuayaba** [sueppchen/PixMob_waveband#5]
The only version of the CC1101 transceiver at my disposal is the one in the attached image, which has a completely different pin mapping and naming, not to mention it has two pins less. Supposing that this component is capable of the same things as the one referred to on this project, I'd appreciate if a mapping for this other one.

![S3a20f6cd36014b0b912827cf9f573c7fm jpg_](https://github.com/sueppchen/PixMob_waveband/assets/12765867/ed363308-7cdb-4e5c-bb0b-634f315eb6af)

**Comment by sueppchen** [comment]
see readme.md --> basic.ino 

MISO (master in slave out) is sometimes called SO (slave out)
MOSI (master out slave in)  is sometimes called SI (slave in)
CS (chip select) is sometimes called CSN (chip select not) because it's active low sometimes SS (slave select)
CLK (clock) is sometimes called SCLK (serial clock)

don't forget the voltage regulator and level-shifter for 3.3V

**Comment by sueppchen** [comment]
I updated the connection page in the wiki: [here](https://github.com/sueppchen/PixMob_waveband/wiki/connection)

**Comment by ElGuayaba** [comment]
Awesome! Thanks a lot for the quick support 🙏
